# Copyright (c) JSCL Kernel Contributors.
# Distributed under the terms of the GPL-3.0-or-later License.

[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v
